CREATE TABLE IF NOT EXISTS Student ( 
                    id BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL , 
                    name VARCHAR(45) NULL,  
                    surname VARCHAR(45) NULL,  
                    patronymic VARCHAR(45) NULL, 
                    birthday DATE NULL, 
                    group_id INT , 
                    PRIMARY KEY (id) , 
                    FOREIGN KEY (group_id) REFERENCES StudentGroup(id) ON DELETE RESTRICT);